# Generated by Django 2.2.1 on 2019-08-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kairymduuluk',
            name='bilim_aluu',
            field=models.IntegerField(default=0, verbose_name='Билим алууга'),
        ),
        migrations.AddField(
            model_name='kairymduuluk',
            name='kurbandyk',
            field=models.IntegerField(default=0, verbose_name='Лурбандыкка'),
        ),
        migrations.AddField(
            model_name='kairymduuluk',
            name='muktaj',
            field=models.IntegerField(default=0, verbose_name='Муктаждарга'),
        ),
        migrations.AddField(
            model_name='kairymduuluk',
            name='suu_chygaruu',
            field=models.IntegerField(default=0, verbose_name='Суу чыгарууга'),
        ),
    ]
