# Generated by Django 2.2.1 on 2019-07-31 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.ForeignKey(blank=True, default='Жаңылыктар', null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Category', verbose_name='Категория'),
        ),
    ]
