# Generated by Django 2.2.1 on 2019-08-05 01:02

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190805_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofonde',
            name='bagyt',
        ),
        migrations.RemoveField(
            model_name='ofonde',
            name='baikoochu',
        ),
        migrations.RemoveField(
            model_name='ofonde',
            name='ish',
        ),
        migrations.RemoveField(
            model_name='ofonde',
            name='maksat',
        ),
        migrations.RemoveField(
            model_name='ofonde',
            name='otchet',
        ),
        migrations.CreateModel(
            name='Fondjonundo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Аты')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Багыттар')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Language', verbose_name='Тили')),
            ],
            options={
                'verbose_name': 'Фонддун ачыктамасы',
                'verbose_name_plural': 'Фонддун ачыктамасы',
                'db_table': 'Фонд',
                'ordering': ['-id'],
            },
        ),
    ]
