# Generated by Django 2.2.1 on 2019-08-01 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190801_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fon',
            options={'ordering': ['-id'], 'verbose_name': 'Фон', 'verbose_name_plural': 'Фоны'},
        ),
    ]
