# Generated by Django 2.2.1 on 2019-08-05 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190805_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fon',
            name='kairymduuluk',
        ),
        migrations.RemoveField(
            model_name='fon',
            name='slider_fon',
        ),
    ]
