# Generated by Django 2.2.1 on 2019-07-26 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Альбомдун аты')),
                ('slug', models.CharField(blank=True, max_length=200, verbose_name='Транслит')),
                ('is_public', models.BooleanField(default=True, verbose_name='Көрүнсүн')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомдор',
                'ordering': ['-created'],
            },
        ),
    ]
