# Generated by Django 2.2.1 on 2019-07-26 10:45

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='gallery/', verbose_name='Сүрөт')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Маалымат')),
                ('is_public', models.BooleanField(default=True, verbose_name='Көрүнсүн')),
                ('album', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Album', verbose_name='Албом')),
            ],
            options={
                'verbose_name': 'Сүрөт',
                'verbose_name_plural': 'Сүрөттөр',
                'ordering': ['-id'],
            },
        ),
    ]
