# Generated by Django 2.2.1 on 2019-08-04 01:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Альбомдун аты')),
                ('ru_name', models.CharField(db_index=True, max_length=250, verbose_name='Орусча аты')),
                ('oblojka', models.ImageField(upload_to='album/oblojka/', verbose_name='Альбомдун обложкасы')),
                ('slug', models.CharField(blank=True, max_length=200, verbose_name='Транслит')),
                ('is_public', models.BooleanField(default=True, verbose_name='Көрүнсүн')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомдор',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Видеонун аты')),
                ('ru_name', models.CharField(db_index=True, max_length=250, verbose_name='Орусча аты')),
                ('oblojka', models.ImageField(upload_to='video/', verbose_name='Видеонун обдожкасы')),
                ('slug', models.CharField(blank=True, max_length=200, verbose_name='Транслит')),
                ('video_url', models.CharField(blank=True, max_length=200, verbose_name='Видеонун ссылкасы')),
                ('is_public', models.BooleanField(default=True, verbose_name='Көрүнсүн')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Language', verbose_name='Тили')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видеолор',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Долбоордун аты')),
                ('oblojka', models.ImageField(upload_to='video/', verbose_name='Долбоордун обдожкасы')),
                ('slug', models.CharField(blank=True, max_length=200, verbose_name='Транслит')),
                ('dolboor_url', models.FileField(blank=True, max_length=200, upload_to='files/', verbose_name='Долбоордун ссылкасы')),
                ('is_public', models.BooleanField(default=True, verbose_name='Көрүнсүн')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Language', verbose_name='Тили')),
            ],
            options={
                'verbose_name': 'Долбоор',
                'verbose_name_plural': 'Долбоорлор',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='gallery/', verbose_name='Сүрөт')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Маалымат')),
                ('ru_description', models.TextField(blank=True, null=True, verbose_name='Орусча')),
                ('is_public', models.BooleanField(default=True, verbose_name='Көрүнсүн')),
                ('album', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.Album', verbose_name='Албом')),
            ],
            options={
                'verbose_name': 'Сүрөт',
                'verbose_name_plural': 'Сүрөттөр',
                'ordering': ['-id'],
            },
        ),
    ]
